title: Scott Draves
subtitle: Pioneering AI Artist & Engineering Leader
email: your-email@example.com
description: >-
  Scott Draves: Pioneering AI Artist & Engineering Leader
baseurl: ""
url: "https://draves.ai"


feature_icon_colour: "#69bbff"

collections:
  features:
    order:
      0_pioneering.md
      1_research.md
      2_academic.md
      3_interview.md
      4_open.md
      5_innovative.md

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
